# This file is based on the PALISADE Makefile
# Multi OS makefile (No Windows yet)

UNAME_S := $(shell uname -s)
UNAME_M := $(shell uname -m)
PKG_CONFIG ?= pkg-config

# Compiler + flags
CC ?= clang++
CXX ?= $(CC)
CPPFLAGS += -std=c++17 -fPIC -O3 -Wall -fno-omit-frame-pointer

# Suppress warnings from alignment of STL structs of blocks
ifeq ($(UNAME_S),Linux)
    CPPFLAGS += -Wno-ignored-attributes
endif

# SSE4/AES only on x86_64
ifeq ($(UNAME_M),x86_64)
    CPPFLAGS += -maes -msse4
endif

# Shared library flags
ifeq ($(UNAME_S),Darwin)
    LIBCMD := -dynamiclib -undefined dynamic_lookup
    LIBSUFFIX := .dylib
else
    LIBCMD := -shared -fPIC
    LIBSUFFIX := .so
endif

# Runtime flags
RDYNAMIC := -rdynamic

# librt only on Linux
ifeq ($(UNAME_S),Linux)
    LDFLAGS += -lrt
endif

# ======================================================================
# OpenSSL via pkg-config (fallback to -lssl -lcrypto)
# ======================================================================
OPENSSL_CFLAGS := $(shell $(PKG_CONFIG) --cflags openssl 2>/dev/null)
OPENSSL_LIBS   := $(shell $(PKG_CONFIG) --libs openssl 2>/dev/null)
CPPFLAGS += $(OPENSSL_CFLAGS)
LDFLAGS  += $(if $(OPENSSL_LIBS),$(OPENSSL_LIBS),-lssl -lcrypto)
ifeq ($(UNAME_S),Darwin)
    LDFLAGS += -lc++
endif

#build and bin directory
BUILDDIR := build
BINDIR := bin

LIBCMD += -L/usr/local/lib

#sources folders
EXTLIBDIR := bin/lib
EXTTESTDIR := bin/unittest
EXTDEMODIR := bin/demo

# extentions for source and header files
SRCEXT := cpp
HDREXT := h

$(objects) : %.o : %.cpp

# External libraries
#EXTLIB := -L$(EXTLIBDIR) $(TEST_LIB) -pg ## include profiling
EXTLIB := -L$(EXTLIBDIR) $(TEST_LIB) ## no-profiling

INC := -I src/lib -I test $(OPENSSL_CFLAGS)

#the name of the shared object library
CORELIB := libverisimplepir$(LIBSUFFIX)

# run make for all components. you can run any individual component separately
#  by invoking   "make alltargets"  for example
# each corresponding makefile will make the allxxxx target
all: allcore
# $(RM) -rf bin/serialized/
# mkdir bin/serialized/

alldemos: allcoredemos

testall: testcore

# clean up all components. you can clean any individual compoenent separately
#  by invoking   "make cleantargets"  for example
# each corresponding makefile will make the cleanxxxx target
.PHONEY: clean
clean: cleancore
	@echo 'Cleaning top level autogenerated directories'
	$(RM) -f test/include/gtest/gtest-all.o
	$(RM) -rf bin

include Makefile.src

test/include/gtest/gtest-all.o: test/include/gtest/gtest-all.cc
	$(CC) -c $(CPPFLAGS) -o $@ $<
