# This file is based on the PALISADE Makefile
# Multi OS makefile (No Windows yet)

UNAME_S := $(shell uname -s)
UNAME_M := $(shell uname -m)
HOST_SYSTEM = $(shell uname | cut -f 1 -d_)
SYSTEM ?= $(HOST_SYSTEM)

CPPSTD := -std=c++17 -fPIC 

ifeq ($(SYSTEM),Darwin)
CC := /Users/sofianeazogagh/local/llvm-19.1.7/bin/clang++ $(CPPSTD)
LDFLAGS += -L/Users/sofianeazogagh/local/llvm-19.1.7/lib -Wl,-rpath,/Users/sofianeazogagh/local/llvm-19.1.7/lib, -L/usr/local/lib -L/opt/homebrew/opt/openssl@3/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
CPPFLAGS += -I/Users/sofianeazogagh/local/llvm-19.1.7/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/opt/homebrew/opt/openssl@3/include
LIBSUFFIX := .dylib
LIBCMD := -dynamiclib -undefined suppress -flat_namespace -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
else
CC := clang++ $(CPPSTD) -Wloop-analysis
# Suppress warnings from alignment of STL structs of blocks
CPPFLAGS += -Wno-ignored-attributes 
LIBSUFFIX := .so
LIBCMD := -fPIC -shared -Wl,--export-dynamic,-z,defs
endif

RDYNAMIC := -rdynamic

# librt is Linux-specific, not needed on macOS
ifneq ($(SYSTEM),Darwin)
LDFLAGS += -lrt
endif

#main best performance configuration for parallel operation - cross-platform
CPPFLAGS += -O3
# CPPFLAGS += -O0 -g
CPPFLAGS += -Wall -fno-omit-frame-pointer
# SSE4 and AES instructions are only available on x86_64
ifeq ($(UNAME_M),x86_64)
CPPFLAGS += -maes -msse4
endif

#build and bin directory
BUILDDIR := build
BINDIR := bin

LDFLAGS += -lssl -lcrypto
ifeq ($(SYSTEM),Darwin)
LIBCMD += -L/opt/homebrew/opt/openssl@3/lib
else
LIBCMD += -L/usr/include/openssl/
LIBCMD += -L/usr/lib/x86_64-linux-gnu
endif
LIBCMD += -L/usr/local/lib

#sources folders
EXTLIBDIR := bin/lib
EXTTESTDIR := bin/unittest
EXTDEMODIR := bin/demo

# extentions for source and header files
SRCEXT := cpp
HDREXT := h

$(objects) : %.o : %.cpp

# External libraries
#EXTLIB := -L$(EXTLIBDIR) $(TEST_LIB) -pg ## include profiling
EXTLIB := -L$(EXTLIBDIR) $(TEST_LIB) ## no-profiling

INC := -I src/lib -I test

#the name of the shared object library
CORELIB := libverisimplepir$(LIBSUFFIX)

# run make for all components. you can run any individual component separately
#  by invoking   "make alltargets"  for example
# each corresponding makefile will make the allxxxx target
all: allcore
# $(RM) -rf bin/serialized/
# mkdir bin/serialized/

alldemos: allcoredemos

testall: testcore

# clean up all components. you can clean any individual compoenent separately
#  by invoking   "make cleantargets"  for example
# each corresponding makefile will make the cleanxxxx target
.PHONEY: clean
clean: cleancore
	@echo 'Cleaning top level autogenerated directories'
	$(RM) -f test/include/gtest/gtest-all.o
	$(RM) -rf bin

include Makefile.src

test/include/gtest/gtest-all.o: test/include/gtest/gtest-all.cc
	$(CC) -c $(CPPFLAGS) -o $@ $<
